# Generated by Django 5.0.4 on 2024-05-07 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_investment', '0004_alter_investment_avg_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investment',
            name='buying_prices',
        ),
        migrations.RemoveField(
            model_name='investment',
            name='selling_prices',
        ),
    ]
