# Generated by Django 5.0.4 on 2024-05-07 18:27

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_investment", "0005_remove_investment_buying_prices_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="investment",
            name="buying_prices",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.JSONField(default={}), default=list, size=None
            ),
        ),
        migrations.AddField(
            model_name="investment",
            name="selling_prices",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.JSONField(default={}), default=list, size=None
            ),
        ),
    ]
