# Generated by Django 5.0.4 on 2024-05-08 06:39

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_investment", "0006_investment_buying_prices_investment_selling_prices"),
    ]

    operations = [
        migrations.AlterField(
            model_name="investment",
            name="buying_prices",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.JSONField(default=dict), default=list, size=None
            ),
        ),
        migrations.AlterField(
            model_name="investment",
            name="selling_prices",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.JSONField(default=dict), default=list, size=None
            ),
        ),
    ]
