# Generated by Django 5.0.4 on 2024-05-21 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user_investment", "0009_remove_investment_broker_brokerinvestment_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="brokerinvestment",
            name="buying_prices",
        ),
        migrations.RemoveField(
            model_name="brokerinvestment",
            name="quantities",
        ),
    ]
