# Generated by Django 5.0.4 on 2024-05-23 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user_investment", "0014_remove_investment_unique_security_user_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="investment",
            name="broker_investments",
        ),
        migrations.DeleteModel(
            name="BrokerInvestment",
        ),
    ]
