# Generated by Django 5.0.4 on 2024-08-22 11:30

import datahub.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_investment", "0016_sectorwiseportfolio"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="investment",
            name="buying_prices",
        ),
        migrations.RemoveField(
            model_name="investment",
            name="selling_prices",
        ),
        migrations.CreateModel(
            name="Transactions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField(default=0)),
                (
                    "price",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=12, null=True
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("credit", "Credit"), ("debit", "Debit")],
                        help_text="Transaction type",
                        max_length=100,
                    ),
                ),
                ("trade_date", models.DateField()),
                (
                    "data",
                    models.JSONField(
                        default=dict, encoder=datahub.models.CustomJSONEncoder
                    ),
                ),
                (
                    "investment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transactions",
                        to="user_investment.investment",
                    ),
                ),
            ],
        ),
    ]
