# Generated by Django 5.0.4 on 2024-10-04 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_investment", "0020_stocktransactions_transaction_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="stocktransactions",
            name="broker",
            field=models.CharField(
                choices=[("groww", "Groww"), ("zerodha", "Zerodha")],
                default="groww",
                max_length=100,
            ),
        ),
    ]
