# Generated by Django 5.0.4 on 2024-04-23 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("datahub", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="security",
            name="isin",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="security",
            name="symbol",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
