# Generated by Django 5.0.4 on 2024-04-23 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("datahub", "0002_security_isin_security_symbol"),
    ]

    operations = [
        migrations.AddField(
            model_name="security",
            name="scrip_code",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
