# Generated by Django 5.0.4 on 2024-04-23 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("datahub", "0004_industry_delete_sector_security_industry"),
    ]

    operations = [
        migrations.AlterField(
            model_name="security",
            name="last_updated_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=6, null=True
            ),
        ),
    ]
