# Generated by Django 5.0.4 on 2024-04-24 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("datahub", "0006_security_historical_price_info"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="security",
            name="industry",
        ),
        migrations.DeleteModel(
            name="Industry",
        ),
    ]
