# Generated by Django 5.0.4 on 2024-04-24 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("datahub", "0009_security_metadata_security_security_info"),
    ]

    operations = [
        migrations.AlterField(
            model_name="security",
            name="name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="security",
            name="symbol",
            field=models.CharField(default="asd", max_length=100),
            preserve_default=False,
        ),
    ]
