# Generated by Django 5.0.4 on 2024-04-24 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("datahub", "0010_alter_security_name_alter_security_symbol"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="security",
            name="symbol",
        ),
    ]
