# Generated by Django 5.0.4 on 2024-04-24 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("datahub", "0011_remove_security_symbol"),
    ]

    operations = [
        migrations.AddField(
            model_name="security",
            name="symbol",
            field=models.CharField(default="aa", max_length=100),
            preserve_default=False,
        ),
    ]
