# Generated by Django 5.0.4 on 2024-04-24 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("datahub", "0015_alter_security_symbol"),
    ]

    operations = [
        migrations.CreateModel(
            name="SecurityCache",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("symbol", models.CharField(max_length=100)),
            ],
        ),
    ]
