# Generated by Django 5.0.4 on 2024-05-03 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("datahub", "0016_securitycache"),
    ]

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                ("author_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
            ],
        ),
    ]
