# Generated by Django 5.0.4 on 2024-05-07 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("datahub", "0017_author"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Author",
        ),
    ]
