# Generated by Django 5.0.4 on 2024-05-07 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("datahub", "0018_delete_author"),
    ]

    operations = [
        migrations.CreateModel(
            name="GeneralInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tradebook_last_uploaded", models.DateField(blank=True, null=True)),
            ],
        ),
    ]
