# Generated by Django 5.0.4 on 2024-05-08 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("datahub", "0019_generalinfo"),
    ]

    operations = [
        migrations.CreateModel(
            name="Parameter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("time", models.TimeField(blank=True, null=True)),
                ("value", models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
