# Generated by Django 5.0.4 on 2024-05-10 06:37

import datahub.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datahub', '0021_stockindex'),
    ]

    operations = [
        migrations.CreateModel(
            name='TodayStockIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('time', models.TimeField(blank=True, null=True)),
                ('historical_dates_info', models.JSONField(default=dict, encoder=datahub.models.CustomJSONEncoder)),
                ('date_30_day_ago', models.DateField(blank=True, null=True)),
                ('data_365_day_ago', models.DateField(blank=True, null=True)),
                ('stocks_indices', models.ManyToManyField(blank=True, null=True, related_name='todays_stock_index', to='datahub.stockindex')),
            ],
        ),
    ]
