# Generated by Django 5.0.4 on 2024-05-10 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datahub', '0028_alter_security_last_updated_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='security',
            name='last_updated_price',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=30, null=True),
        ),
    ]
