# Generated by Django 5.0.4 on 2024-05-13 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datahub', '0029_alter_security_last_updated_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='security',
            name='base_security',
            field=models.BooleanField(default=False),
        ),
    ]
