# Generated by Django 5.0.4 on 2024-05-13 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("datahub", "0030_security_base_security"),
    ]

    operations = [
        migrations.AlterField(
            model_name="security",
            name="base_security",
            field=models.BooleanField(default=True),
        ),
    ]
