# Generated by Django 5.0.4 on 2024-05-15 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("datahub", "0034_security_event"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="security",
            name="event",
        ),
    ]
