# Generated by Django 5.0.4 on 2024-05-26 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("datahub", "0036_holidays"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Holidays",
            new_name="Holiday",
        ),
    ]
