# Generated by Django 5.0.4 on 2024-05-28 11:26

import datahub.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("datahub", "0037_rename_holidays_holiday"),
    ]

    operations = [
        migrations.CreateModel(
            name="TodaysMacroSectorPerformance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("datetime", models.DateTimeField(auto_now_add=True)),
                (
                    "data",
                    models.JSONField(
                        default=dict, encoder=datahub.models.CustomJSONEncoder
                    ),
                ),
            ],
        ),
    ]
