# Generated by Django 5.0.4 on 2024-08-30 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("datahub", "0038_todaysmacrosectorperformance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stockindex",
            name="date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="stockindex",
            name="time",
            field=models.TimeField(),
        ),
    ]
