# Generated by Django 5.0.4 on 2024-08-30 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("datahub", "0039_alter_stockindex_date_alter_stockindex_time"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="stockindex",
            unique_together={("index", "date", "time")},
        ),
    ]
