# Generated by Django 5.0.4 on 2024-08-30 09:57

import datahub.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("datahub", "0040_alter_stockindex_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="security",
            name="free_float_market_cap",
            field=models.DecimalField(
                blank=True, decimal_places=10, max_digits=30, null=True
            ),
        ),
        migrations.AddField(
            model_name="security",
            name="market_cap",
            field=models.DecimalField(
                blank=True, decimal_places=10, max_digits=30, null=True
            ),
        ),
        migrations.AddField(
            model_name="security",
            name="trade_info",
            field=models.JSONField(
                default=dict, encoder=datahub.models.CustomJSONEncoder
            ),
        ),
    ]
