# Generated by Django 5.0.4 on 2024-09-30 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("datahub", "0041_security_free_float_market_cap_security_market_cap_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CorporateAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("symbol", models.CharField(max_length=20)),
                ("series", models.CharField(max_length=10)),
                ("ind", models.CharField(blank=True, max_length=10, null=True)),
                ("face_val", models.DecimalField(decimal_places=2, max_digits=10)),
                ("subject", models.CharField(max_length=255)),
                ("ex_date", models.DateField()),
                ("rec_date", models.DateField(blank=True, null=True)),
                ("bc_start_date", models.DateField(blank=True, null=True)),
                ("bc_end_date", models.DateField(blank=True, null=True)),
                ("nd_start_date", models.DateField(blank=True, null=True)),
                ("comp", models.CharField(max_length=255)),
                ("isin", models.CharField(max_length=12)),
                ("nd_end_date", models.DateField(blank=True, null=True)),
                ("ca_broadcast_date", models.DateField(blank=True, null=True)),
                (
                    "security",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="corporate_actions",
                        to="datahub.security",
                    ),
                ),
            ],
            options={
                "unique_together": {("security_id", "ex_date", "subject")},
            },
        ),
    ]
