# Generated by Django 5.0.4 on 2024-09-30 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("datahub", "0043_corporateaction_corporate_action_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="corporateaction",
            name="dividend",
            field=models.FloatField(default=0.0),
        ),
    ]
