# Generated by Django 5.0.4 on 2024-04-24 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("industries", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="basicindustry",
            old_name="sector",
            new_name="industry",
        ),
    ]
