# Generated by Django 5.0.4 on 2024-05-28 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("industries", "0003_alter_basicindustry_basic_ind_code"),
    ]

    operations = [
        migrations.CreateModel(
            name="TodaysMacroSectorPerformance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("datetime", models.DateTimeField(auto_now_add=True)),
                ("data", models.JSONField(default=dict)),
            ],
        ),
    ]
