# Generated by Django 5.0.4 on 2024-05-28 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("industries", "0004_todaysmacrosectorperformance"),
    ]

    operations = [
        migrations.DeleteModel(
            name="TodaysMacroSectorPerformance",
        ),
    ]
