# Generated by Django 5.0.4 on 2024-05-15 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=500)),
                ('purpose', models.CharField(max_length=100)),
                ('details', models.TextField(blank=True, null=True)),
                ('date', models.DateField()),
            ],
        ),
    ]
