# Generated by Django 5.0.4 on 2024-05-20 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groww', '0002_alter_growwrequest_headers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='growwrequest',
            name='headers',
            field=models.JSONField(),
        ),
    ]
