# Generated by Django 5.0.4 on 2024-05-20 19:34

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groww', '0003_alter_growwrequest_headers'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GrowwRequest',
            new_name='GrowwRequestHeader',
        ),
    ]
