# Generated by Django 5.0.4 on 2024-09-09 11:21

import datahub.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("groww", "0005_growwrequestheader_method"),
    ]

    operations = [
        migrations.CreateModel(
            name="GrowwRequestError",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("datetime", models.DateTimeField(auto_created=True)),
                ("url", models.URLField(blank=True, null=True)),
                (
                    "data",
                    models.JSONField(
                        default=dict, encoder=datahub.models.CustomJSONEncoder
                    ),
                ),
            ],
        ),
    ]
