# Generated by Django 5.0.4 on 2024-04-24 08:20

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0003_alter_investment_avg_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="investment",
            name="buying_prices",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.DecimalField(decimal_places=2, max_digits=6),
                default=[],
                size=None,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="investment",
            name="selling_prices",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.DecimalField(decimal_places=2, max_digits=6),
                default=[],
                size=None,
            ),
            preserve_default=False,
        ),
    ]
