# Generated by Django 5.0.4 on 2024-04-24 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0004_investment_buying_prices_investment_selling_prices"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Investment",
        ),
    ]
