# Generated by Django 5.0.4 on 2024-04-19 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_import", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UploadedContractNotePDF",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pdf_file", models.FileField(upload_to="pdf_files/contract_notes/")),
                ("processed", models.BooleanField(default=False)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="UploadedDematReportPDF",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pdf_file", models.FileField(upload_to="pdf_files/contract_notes/")),
                ("processed", models.BooleanField(default=False)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name="UploadedPDF",
        ),
    ]
