# Generated by Django 5.0.4 on 2024-04-23 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_import", "0005_uploadedcontractnotepdf_broker"),
        ("datahub", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="uploadeddematreportpdf",
            name="broker",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="datahub.broker",
            ),
        ),
    ]
