# Generated by Django 5.0.4 on 2024-04-24 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_import", "0007_alter_tradebook_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tradebook",
            name="exchange",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="tradebook",
            name="security",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
