# Generated by Django 5.0.4 on 2024-04-24 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_import", "0009_alter_investmentbook_security"),
    ]

    operations = [
        migrations.AddField(
            model_name="investmentbook",
            name="investment_processed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="tradebook",
            name="investment_processed",
            field=models.BooleanField(default=False),
        ),
    ]
