# Generated by Django 5.0.4 on 2024-04-24 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_import", "0010_investmentbook_investment_processed_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tradebook",
            name="order_time",
        ),
        migrations.RemoveField(
            model_name="tradebook",
            name="trade_time",
        ),
        migrations.AddField(
            model_name="tradebook",
            name="execution_datetime",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tradebook",
            name="isin",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="tradebook",
            name="symbol",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="tradebook",
            name="buy_sell",
            field=models.CharField(
                choices=[("B", "Buy"), ("S", "Sell"), ("buy", "Buy"), ("sell", "Sell")],
                default="B",
                max_length=10,
            ),
        ),
    ]
