# Generated by Django 5.0.4 on 2024-04-24 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_import", "0011_remove_tradebook_order_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tradebook",
            name="buy_sell",
            field=models.CharField(default="B", max_length=10),
        ),
    ]
