# Generated by Django 5.0.4 on 2024-04-24 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_import", "0014_uploadedcontractnotepdf_password_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="uploadedcontractnotepdf",
            name="broker",
            field=models.CharField(
                blank=True,
                choices=[("groww", "Groww"), ("zerodha", "Zerodha")],
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="uploadeddematreportpdf",
            name="broker",
            field=models.CharField(
                blank=True,
                choices=[("groww", "Groww"), ("zerodha", "Zerodha")],
                max_length=100,
                null=True,
            ),
        ),
    ]
