# Generated by Django 5.0.4 on 2024-05-20 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_import', '0022_mutualfundbook'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mutualfundbook',
            name='processed',
        ),
    ]
