# Generated by Django 5.0.4 on 2024-05-20 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_import', '0023_remove_mutualfundbook_processed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mutualfundbook',
            name='amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mutualfundbook',
            name='nav',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mutualfundbook',
            name='units',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
