# Generated by Django 5.0.4 on 2024-05-20 13:46

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mutual_funds', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MutualFundInvestment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avg_nav', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
                ('units', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
                ('units_purchased', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), default=list, size=None)),
                ('nav_purchased', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), default=list, size=None)),
                ('fund', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='investments', to='mutual_funds.fund')),
            ],
        ),
    ]
