# Generated by Django 5.0.4 on 2024-05-25 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mutual_funds', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name="Fund",
        ),

    ]
