# Generated by Django 5.0.4 on 2024-05-20 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mutual_funds', '0002_mutualfundinvestment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MutualFundInvestment',
            new_name='FundInvestment',
        ),
    ]
