# Generated by Django 5.0.4 on 2024-05-20 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mutual_funds', '0004_fundinvestment_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundinvestment',
            name='avg_nav',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fundinvestment',
            name='units',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
