# Generated by Django 5.0.4 on 2024-05-20 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mutual_funds', '0005_alter_fundinvestment_avg_nav_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundinvestment',
            name='units',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
