# Generated by Django 5.0.4 on 2024-05-20 14:50

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mutual_funds', '0006_alter_fundinvestment_units'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundinvestment',
            name='avg_nav',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='fundinvestment',
            name='nav_purchased',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=5, default=0, max_digits=10), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='fundinvestment',
            name='units',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='fundinvestment',
            name='units_purchased',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=5, default=0, max_digits=10), default=list, size=None),
        ),
    ]
