# Generated by Django 5.0.4 on 2024-05-25 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mutual_funds", "0006_fundinvestment_amount_invested_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="fundsecurity",
            options={"verbose_name_plural": "Fund Securities"},
        ),
    ]
