# Generated by Django 5.0.4 on 2024-05-20 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mutual_funds', '0007_alter_fundinvestment_avg_nav_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundinvestment',
            name='units',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=10),
        ),
    ]
