# Generated by Django 5.0.4 on 2024-05-21 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mutual_funds', '0008_alter_fundinvestment_units'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fundinvestment',
            name='fund',
        ),
        migrations.DeleteModel(
            name='Fund',
        ),
    ]
