# Generated by Django 5.0.4 on 2024-05-25 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mutual_funds', '0009_fundtransaction_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundinvestment',
            name='transactions',
            field=models.ManyToManyField(related_name='fund_investment', to='mutual_funds.fundtransaction'),
        ),
    ]
