# Generated by Django 5.0.4 on 2024-05-25 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mutual_funds", "0014_sipdetails_remove_fundinvestment_folio_number_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fundinvestmentfolio",
            name="current_nav_date",
        ),
    ]
