# Generated by Django 5.0.4 on 2024-08-23 07:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mutual_funds", "0016_remove_fundinvestment_nav_purchased_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="fund",
            name="last_updated",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="fundinvestmentfolio",
            name="folio_number",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
