# Generated by Django 5.0.4 on 2024-09-05 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mutual_funds", "0017_fund_last_updated_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="fund",
            name="five_year_returns",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="fund",
            name="one_year_returns",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="fund",
            name="three_year_returns",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
